version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_task
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:rootpass@db:3306/test_task
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
      wait-for-it db:3306 -- &&
      npm install &&
      npm run build &&
      npx prisma migrate dev &&
      npx ts-node prisma/seed.ts &&
      npm start"
    restart: on-failure
  

volumes:
  db_data:
